//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "attendee")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub capid: i32,
    pub rank: String,
    pub last_name: String,
    pub first_name: String,
    pub middle_name: Option<String>,
    pub unit: String,
    pub gender: String,
    pub date_of_birth: Date,
    pub age_at_start: i32,
    pub age_at_end: i32,
    pub height: Option<i32>,
    pub weight: Option<i32>,
    pub shirt_size: Option<String>,
    pub member_type: String,
    pub expiration: Date,
    pub member_status: String,
    pub home_phone: Option<String>,
    pub cell_phone: Option<String>,
    pub email: String,
    pub address1: String,
    pub address2: String,
    pub city: String,
    pub state: String,
    pub zip_code: String,
    pub registration_status: String,
    pub is_staff: bool,
    pub registration_id: i32,
    pub comments: Option<String>,
    pub emergency_contact_name: Option<String>,
    pub emergency_contact_number: Option<String>,
    pub cadet_parent_phone_primary: Option<String>,
    pub cadet_parent_phone_secondary: Option<String>,
    pub cadet_parent_email_primary: Option<String>,
    pub cadet_parent_email_secondary: Option<String>,
    pub unit_commander_name: String,
    pub unit_commander_email: String,
    pub wing_commander_name: String,
    pub wing_commander_email: String,
    pub is_pilot: bool,
    pub dl_expiration: Option<Date>,
    pub last_encampment: Option<Date>,
    pub highest_o_ride: Option<i32>,
    pub aircraft_ground_handling: Option<Date>,
    pub wing_runner: Option<Date>,
    pub orm_basic: Option<Date>,
    pub orm_intermediate: Option<Date>,
    pub cppt_expiration: Option<Date>,
    pub monthly_safety: Option<Date>,
    pub icut: Option<Date>,
    pub is100: Option<Date>,
    pub is700: Option<Date>,
    pub capt116: Option<Date>,
    pub capt117_part1: Option<Date>,
    pub capt117_part2: Option<Date>,
    pub capt117_part3: Option<Date>,
    pub first_aid: Option<Date>,
    pub invoice_id: Option<i32>,
    pub prices_id: Option<i32>,
    pub invoice_status: Option<String>,
    pub registered_by: Option<String>,
    #[sea_orm(has_many, via = "headcount_entry")]
    pub headcount_entries: HasMany<super::headcount::Entity>,
    #[sea_orm(has_many)]
    pub issued_radios: HasMany<super::radio::Entity>,
    #[sea_orm(has_many)]
    pub issued_vehicles: HasMany<super::vehicle::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
