//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "headcount_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "capid")]
    pub headcount_id: i32,
    #[sea_orm(unique_key = "capid")]
    pub capid: i32,
    #[sea_orm(
        belongs_to,
        from = "capid",
        to = "capid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub attendee: HasOne<super::attendee::Entity>,
    #[sea_orm(
        belongs_to,
        from = "headcount_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub headcount: HasOne<super::headcount::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
