//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "headcount")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub location: String,
    pub created_at: DateTime,
    #[sea_orm(has_many, via = "headcount_entry")]
    pub attendees: HasMany<super::attendee::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
