//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "headcount")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub location: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::headcount_entry::Entity")]
    HeadcountEntry,
    #[sea_orm(has_many = "super::attendee::Entity")]
    Attendee,
}

impl Related<super::headcount_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HeadcountEntry.def()
    }
}

impl Related<super::attendee::Entity> for Entity {
    fn to() -> RelationDef {
        super::headcount_entry::Relation::Attendee.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::headcount_entry::Relation::Headcount.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
