//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "headcount_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub headcount_id: i32,
    pub capid: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attendee::Entity",
        from = "Column::Capid",
        to = "super::attendee::Column::Capid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Attendee,
    #[sea_orm(
        belongs_to = "super::headcount::Entity",
        from = "Column::HeadcountId",
        to = "super::headcount::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Headcount,
}

impl Related<super::attendee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attendee.def()
    }
}

impl Related<super::headcount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Headcount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
