//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod attendee;
pub mod headcount;
pub mod headcount_entry;
pub mod radio;
pub mod radio_type;
pub mod vehicle;
pub mod vehicle_inspection;
pub mod vehicle_type;
