//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::attendee::Entity as Attendee;
pub use super::headcount::Entity as Headcount;
pub use super::headcount_entry::Entity as HeadcountEntry;
