//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "radio_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub make: String,
    pub model: String,
    #[sea_orm(has_many)]
    pub radios: HasMany<super::radio::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
