//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "radio_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub make: String,
    pub model: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::radio::Entity")]
    Radio,
}

impl Related<super::radio::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Radio.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
