//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "radio")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub type_id: i32,
    pub property_tag_number: String,
    pub owned_by_unit: String,
    pub issued_to: Option<i32>,
    pub in_service: bool,
    #[sea_orm(
        belongs_to,
        from = "issued_to",
        to = "capid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub holder: HasOne<super::attendee::Entity>,
    #[sea_orm(
        belongs_to,
        from = "type_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_type: HasOne<super::radio_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
