//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "radio")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub type_id: i32,
    pub property_tag_number: String,
    pub owned_by_unit: String,
    pub issued_to: Option<i32>,
    pub in_service: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::radio_type::Entity")]
    RadioType,
    #[sea_orm(has_one = "super::attendee::Entity")]
    IssuedTo,
}

impl Related<super::radio_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioType.def()
    }
}

impl Related<super::attendee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssuedTo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
