//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vehicle_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub make: String,
    pub model: String,
    pub capacity: i32,
    #[sea_orm(has_many)]
    pub vehicles: HasMany<super::vehicle::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
